### ISSUE TITLE
Failures on [co19] Roll co19 to 5182a15ce02779832377ec02c35bd174acd875ac

### ISSUE THREAD

**Issue by athomas** [dart-lang/co19#951]
There are new test failures on [[co19] Roll co19 to 5182a15ce02779832377ec02c35bd174acd875ac](https://dart-review.googlesource.com/c/sdk/+/166632).

The tests
```
co19/LanguageFeatures/nnbd/local_variable_read_A01_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/local_variable_read_A02_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/local_variable_read_A03_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/local_variable_read_A04_t02 Pass (expected StaticWarning)
co19/LanguageFeatures/nnbd/local_variable_read_A04_t07 Pass (expected StaticWarning)
co19/LanguageFeatures/nnbd/local_variable_read_A04_t08 Pass (expected StaticWarning)
co19/LanguageFeatures/nnbd/local_variable_read_A04_t09 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/local_variable_read_A05_t02 MissingCompileTimeError (expected Pass)
```
are failing on configurations
```
analyzer-asserts-strong-linux
analyzer-asserts-strong-mac
analyzer-asserts-strong-win
analyzer-asserts-weak-mac
analyzer-asserts-weak-win
cfe-strong-linux
cfe-strong-mac
cfe-strong-win
cfe-weak-mac
cfe-weak-win
dart2js-hostasserts-strong-linux-x64-chrome
dartdevk-strong-linux-release-chrome
dartk-strong-linux-debug-ia32
dartk-strong-linux-debug-x64
dartk-strong-linux-release-ia32
dartk-strong-linux-release-simarm
dartk-strong-linux-release-simarm64
dartk-strong-linux-release-x64
dartk-strong-mac-debug-x64
dartk-strong-mac-release-x64
dartk-strong-win-debug-x64
dartk-strong-win-release-ia32
dartk-strong-win-release-x64
dartkp-strong-linux-debug-x64
dartkp-strong-linux-release-simarm64
dartkp-strong-linux-release-x64
dartkp-strong-mac-release-simarm64
dartkp-strong-win-release-x64
```

**Comment by sgrekhov** [comment]
@athomas most of the failures have been already fixed by e669fa6c1eb1fdd3e53e641ef0f74488bb123764. 
What I cannot explain are failures of 
[co19/LanguageFeatures/nnbd/local_variable_read_A04_t02](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/local_variable_read_A04_t02.dart) Pass (expected StaticWarning)
[co19/LanguageFeatures/nnbd/local_variable_read_A04_t07](https://github.com/dart-lang/co19/blob/master/LanguageFeatures/nnbd/local_variable_read_A04_t07.dart) Pass (expected StaticWarning)

```dart
/*
...
 * @ static-warning
*/
...
  late int x12;
  x12 ??= 2;
//^^
// [analyzer] unspecified
// [cfe] unspecified
...
```
Here we expect compile error and warning at the same time (code produces both error and warning) on both analyzer and CFE. But on `analyzer-...` configuration it fails as missing StaticError. And there is no failure on `front-end-..` configuration. Do you know what should be changed in the test to make them working?

**Comment by athomas** [comment]
@eernstg Can you answer @sgrekhov's question?

**Comment by eernstg** [comment]
I get both the warning and the error when running this as a standalone example. So it seems to be associated with the test running behavior. Have you tried this?:

```dart
  late int x12;
  /**/ x12 ??= 2;
  //   ^^^
  // [analyzer] COMPILE_TIME_ERROR.DEFINITELY_UNASSIGNED_LATE_LOCAL_VARIABLE
  //           ^
  // [analyzer] STATIC_WARNING.DEAD_NULL_AWARE_EXPRESSION
  // [cfe] unspecified
```

**Comment by athomas** [comment]
```
co19/LanguageFeatures/nnbd/local_variable_read_A01_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/local_variable_read_A02_t03 CompileTimeError (expected Pass)
co19/LanguageFeatures/nnbd/local_variable_read_A03_t03 CompileTimeError (expected Pass)
```
Didn't change on the new roll either, so they are also still failing. https://dart-ci.firebaseapp.com/cl/166638/1

**Comment by sgrekhov** [comment]
They are failing because of triple shift operation. They'll be turned off in a .status file in upcoming CL. I have no notification about a new roll. Is it in progress?

**Comment by sgrekhov** [comment]
@eernstg tryed this. Problem is that I had no this failure on edge version of SDK before and have no failure now. Let's wait for the new roll and see if it will be resolved

**Comment by athomas** [comment]
On the new roll, this didn't change:
http://dart-review.googlesource.com/c/sdk/+/166848/1

When you say you don't see the failure, how did you run the test?

**Comment by sgrekhov** [comment]
@athomas I do the following
```
sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$ gclient sync
...
sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$ ./tools/build.py --no-goma --mode release --arch x64 create_sdk
...
sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$ tools/test.py -n analyzer-asserts-strong-linux co19/LanguageFeatures/nnbd/local_variable_read_A04_t07
Test configuration:
    analyzer-asserts-strong-linux(architecture: x64, compiler: dart2analyzer, mode: release, runtime: none, system: linux, nnbd: strong, enable-asserts, use-sdk)
Suites tested: co19
[00:06 | 100% | +    1 | -    0]

=== All 1 test passed ===
sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$ tools/test.py -n analyzer-asserts-strong-linux co19/LanguageFeatures/nnbd/local_variable_read_A04_t02
Test configuration:
    analyzer-asserts-strong-linux(architecture: x64, compiler: dart2analyzer, mode: release, runtime: none, system: linux, nnbd: strong, enable-asserts, use-sdk)
Suites tested: co19
[00:04 | 100% | +    1 | -    0]

=== All 1 test passed ===

sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$ cat tests/co19/src/LanguageFeatures/nnbd/local_variable_read_A04_t07.dart
...
  late int x12;
  x12 ??= 2;
//^^^
// [analyzer] COMPILE_TIME_ERROR.DEFINITELY_UNASSIGNED_LATE_LOCAL_VARIABLE
//        ^
// [analyzer] STATIC_WARNING.DEAD_NULL_AWARE_EXPRESSION
// [cfe] unspecified
}

```
So I have the latest version of SDK and tests (with the last changes suggested by Erik).  Do you have the same results?

**Comment by sgrekhov** [comment]
@athomas  I retested on my enviroment one more time. Steps:
```
sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$ git pull
...
sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$ gclient sync
...
sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$ rm -r out/ReleaseX64
sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$  ./tools/build.py --no-goma --mode release --arch x64 create_sdk

sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$ tools/test.py -n analyzer-asserts-strong-linux co19/LanguageFeatures/nnbd/local_variable_read_A04_t07
Test configuration:
    analyzer-asserts-strong-linux(architecture: x64, compiler: dart2analyzer, mode: release, runtime: none, system: linux, nnbd: strong, enable-asserts, use-sdk)
Suites tested: co19
[00:07 | 100% | +    1 | -    0]

=== All 1 test passed ===

sergey@sgrekhov-ubuntu:~/dart-sdk/sdk$ tools/test.py -n analyzer-asserts-strong-linux -v co19/LanguageFeatures/nnbd/local_variable_read_A04_t07
Test configuration:
    analyzer-asserts-strong-linux(architecture: x64, compiler: dart2analyzer, mode: release, runtime: none, system: linux, nnbd: strong, enable-asserts, use-sdk)
Suites tested: co19
Running "dart2analyzer" command: DART_CONFIGURATION=ReleaseX64 out/ReleaseX64/dart-sdk/bin/dartanalyzer --ignore-unrecognized-flags --packages=/home/sergey/dart-sdk/sdk/.packages --format=machine --no-hints /home/sergey/dart-sdk/sdk/tests/co19/src/LanguageFeatures/nnbd/local_variable_read_A04_t07.dart
Done dart2analyzer-none release_x64 co19/LanguageFeatures/nnbd/local_variable_read_A04_t07: pass
```
I also tried `--noBatch` option, but result was the same (test passed)
Could you, please, to run this test on your machine? I do believe that it's an odd infra issue
